param([String]$debugfile = "");

# This powershell file has been generated by the IAR Embedded Workbench
# C - SPY Debugger, as an aid to preparing a command line for running
# the cspybat command line utility using the appropriate settings.
#
# Note that this file is generated every time a new debug session
# is initialized, so you may want to move or rename the file before
# making changes.
#
# You can launch cspybat by typing Powershell.exe -File followed by the name of this batch file, followed
# by the name of the debug file (usually an ELF / DWARF or UBROF file).
#
# Read about available command line parameters in the C - SPY Debugging
# Guide. Hints about additional command line parameters that may be
# useful in specific cases :
#   --download_only   Downloads a code image without starting a debug
#                     session afterwards.
#   --silent          Omits the sign - on message.
#   --timeout         Limits the maximum allowed execution time.
#


if ($debugfile -eq "")
{
& "D:\Program Files\Programming Solution\IAR 8051\common\bin\cspybat" -f "D:\Documents\Sync\Dropbox\蓝牙\代码_蓝牙主从一体_12_25 - 副本\BLE\BLE-CC254x-1.3.2-Serial\Projects\ble\SimpleBLECP\CC2540DB\settings\SimpleBLEPeripheral.Image_A.general.xcl" --backend -f "D:\Documents\Sync\Dropbox\蓝牙\代码_蓝牙主从一体_12_25 - 副本\BLE\BLE-CC254x-1.3.2-Serial\Projects\ble\SimpleBLECP\CC2540DB\settings\SimpleBLEPeripheral.Image_A.driver.xcl" 
}
else
{
& "D:\Program Files\Programming Solution\IAR 8051\common\bin\cspybat" -f "D:\Documents\Sync\Dropbox\蓝牙\代码_蓝牙主从一体_12_25 - 副本\BLE\BLE-CC254x-1.3.2-Serial\Projects\ble\SimpleBLECP\CC2540DB\settings\SimpleBLEPeripheral.Image_A.general.xcl" --debug_file=$debugfile --backend -f "D:\Documents\Sync\Dropbox\蓝牙\代码_蓝牙主从一体_12_25 - 副本\BLE\BLE-CC254x-1.3.2-Serial\Projects\ble\SimpleBLECP\CC2540DB\settings\SimpleBLEPeripheral.Image_A.driver.xcl" 
}
